#   Copyright (C) 2024 John Törnblom
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING. If not see
# <http://www.gnu.org/licenses/>.

PS5_HOST ?= ps5

ifdef PS5_PAYLOAD_SDK
    include $(PS5_PAYLOAD_SDK)/toolchain/prospero.mk
else
    $(error PS5_PAYLOAD_SDK is undefined)
endif

CFLAGS := -O1 -Wall -Werror -Wno-unreachable-code-generic-assoc
LDADD := `$(PS5_SYSROOT)/bin/curl-config --cflags --libs`

ELF := fetchpkg.elf

all: $(ELF)

$(ELF): main.c dl.c parson.c
	$(CC) $(CFLAGS) -o $@ $(LDADD) $^

clean:
	rm -f $(ELF)

upload: $(ELF)
	curl -T $^ ftp://$(PS5_HOST):2121/data/$^
