#   Copyright (C) 2024 John Törnblom
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING. If not see
# <http://www.gnu.org/licenses/>.

CC := x86_64-w64-mingw32-gcc

CURL_PATH ?= curl-8.8.0_3-win64-mingw

CFLAGS := -O2 -Wall -D_FILE_OFFSET_BITS=64
CFLAGS += -I$(CURL_PATH)/include  -L$(CURL_PATH)/lib
LDADD  := -lcurl -lws2_32 -lwinmm

EXE := fetchpkg.exe

all: $(EXE)

$(EXE): main.c dl.c parson.c sha256.c sha1.c
	$(CC) $(CFLAGS) -o $@ $^ $(LDADD)

clean:
	rm -f $(EXE)

